version: "3"

services:
  fauxmo:
    container_name: fauxmo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${FAUXMO_UID:-10000}
        - GID=${FAUXMO_GID:-10000}
    restart: unless-stopped
    volumes:
      - "./config.json:/etc/fauxmo/config.json:ro"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: host
    environment:
      - TZ=America/Denver
